version: '3.7'
services:
  selenium-hub:
    image: selenium/hub:3.14.0-curium
    container_name: tempContainer
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - grid
    restart: unless-stopped

networks:
  grid
    